# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Permalinks
permalink: pretty

# Setup
title: gr-bokehgui
tagline: Web based display for GNURadio
url: "http://kartikpatel.in"
baseurl: "/GSoC2017/"
paginate: 5

# Assets
sass:
  sass_dir: _sass
  style:  :compressed

# About/Contact
author:
  name: Kartik Patel
  url:  http://kartikpatel.in/
  email: kartikpatel1995@gmail.com
  description: I am Kartik Patel, a Google Summer of Code 2017 participant at GNU Radio. I will be working on development of a web based display for GNU Radio.

# Custom vars
version: 2.0
github:
  repo:  https://github.com/kartikp1995/gr-bokehgui

# Build settings
gems:
  - jekyll-paginate
  - jekyll-gist
#  - jekyll-feed
#exclude:
#  - Gemfile
#  - Gemfile.lock


